config/routes.rb
ContactForm::Application.routes.draw do

  resources :inquiries

end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base

  validates_presence_of :first_name

  validates_presence_of :last_name

  validates_presence_of :email
  validates_uniqueness_of :email
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  validates_presence_of :subject

  validates_presence_of :description


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :destroy]

  def index
    @inquiries = Inquiry.all
  end

  def new
    @inquiry = Inquiry.new
  end

  def show
  end

  def destroy
    @inquiry.destroy
    flash["alert-box"] = "Inquiry Deleted"
    redirect_to inquiries_path
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      flash["alert-box info radius"] = "Inquiry created successfully"
      redirect_to @inquiry
    else
      flash["alert-box warning radius"] = "Inquiry not created"
      render 'new'
    end
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:first_name, :last_name, :email, :subject, :description)
  end

  def set_inquiry
    @inquiry = Inquiry.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inquiries/index.html.erb
<div>
  <h1>Total Number of Inquiries: <%= @inquiries.count %></h1>
</div>
<br>
<div class='row'>
  <% @inquiries.each do |inquiry| %>
    <ul class='pricing-table'>
      <li class='price'><%= "Inquirer: #{inquiry.first_name} #{inquiry.last_name}"%></li.title>
      <li class='description'><%= "Subject: #{inquiry.subject}"%></li>
      <li class='bullet-item'><%="Description: #{inquiry.description}"%></li>
      <li class="cta-button"><%= link_to "Delete", inquiry_path(inquiry), method: :delete, class: 'button [secondary alert success]' %></li>
    </ul>
  <% end %>
</div>

app/views/inquiries/new.html.erb
<div class='row'>
  <h1>All Inquiries</h1>
</div>

<div class='row'>

  <%= form_for(@inquiry) do |f| %>

  <% if @inquiry.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @inquiry.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>

  <% end %>

    <div>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div>
      <%= f.label :subject %>
      <%= f.text_field :subject %>
    </div>

    <div>
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>

    <div>
      <%= f.submit class: "button [radius round]" %>
    </div>

  <% end %>

</div>

app/views/inquiries/show.html.erb
<div class='row'>
  <h1>Inquiry Subject: </h1>
  <h4><%= @inquiry.subject %><h4>
</div>
<br>

<div class='row'>
  <h1>Name of Inquirer: </h1>
  <h4><%= "#{@inquiry.first_name}  #{@inquiry.last_name}" %><h4>
</div>
<br>

<div class='row'>
  <h1>Email: </h1>
  <h4><%= "#{@inquiry.email}" %><h4>
</div>
<br>

<div class='row'>
  <h1>Description: </h1>
  <p><%= "#{@inquiry.description}" %><p>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

<% flash.each do |name, msg| -%>
    <%= content_tag :div, msg, class: name %>
<% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>